### ISSUE TITLE
version prefix?

### ISSUE THREAD

**Issue by pombredanne** [giterlizzi/perl-URI-PackageURL#14]
I see you are using a "version_prefix" qualifier for github/gitlab/bitbucket PURLs.
I guess you likely took that from the contrib/ folder in the packageurl-python library?

FYI, we are rolling that back there as it was a failed and fraught experiment: https://github.com/package-url/packageurl-python/pull/159/files

I would suggest you also roll this back. Instead just take a full tag as-is, unstripped

**Comment by giterlizzi** [comment]
Thank you for your report. Fixed!
