### ISSUE TITLE
Incorrect parsing of PURLs that begin with `pkg:/`

### ISSUE THREAD

**Issue by matt-phylum** [giterlizzi/perl-URI-PackageURL#6]
The PURL test suite contains the PURLs `pkg:/maven/org.apache.commons/io` `pkg://maven/org.apache.commons/io` `pkg:///maven/org.apache.commons/io`, all of which are supposed to parse successfully to the same package. However, perl-URI-PackageURL fails to parse all three with "Malformed PackageURL string".

**Comment by giterlizzi** [comment]
FIXED in last release of URI::PackageURL

```console
$ purl-tool pkg:///maven/org.apache.commons/io --env
PURL="pkg:maven/org.apache.commons/io"
PURL_TYPE="maven"
PURL_NAMESPACE="org.apache.commons"
PURL_NAME="io"
PURL_VERSION=""
PURL_SUBPATH=""
PURL_QUALIFIERS=""
PURL_REPOSITORY_URL="https://mvnrepository.com/artifact/org.apache.commons/io"
```

Thanks ;)
