### ISSUE TITLE
Qualifiers are case sensitive

### ISSUE THREAD

**Issue by matt-phylum** [giterlizzi/perl-URI-PackageURL#7]
The PURL test suite contains a non-canonical PURL `pkg:gem/jruby-launcher@1.1.2?Platform=java` which is supposed to have the qualifier `platform=java`. perl-URI-PackageURL parses it as `Platform=java`. This can cause problems with code that tries to find a qualifier by its key.

**Comment by giterlizzi** [comment]
FIXED in last release of URI::PackageURL

```console
$ purl-tool pkg:gem/jruby-launcher@1.1.2?Platform=java --env
PURL="pkg:gem/jruby-launcher@1.1.2?platform=java"
PURL_TYPE="gem"
PURL_NAMESPACE=""
PURL_NAME="jruby-launcher"
PURL_VERSION="1.1.2"
PURL_SUBPATH=""
PURL_QUALIFIERS="platform"
PURL_QUALIFIER_platform="java"
PURL_DOWNLOAD_URL="https://rubygems.org/downloads/jruby-launcher-1.1.2.gem"
PURL_REPOSITORY_URL="https://rubygems.org/gems/jruby-launcher/versions/1.1.2"
```

Thanks ;)
